: ' WORD FIND DROP ; LABEL _TICK
: POSTPONE ' COMPILE, ; IMMEDIATE

: ['] A.LIT [ ' A.LIT XT, ] COMPILE, ' XT, ; IMMEDIATE LABEL _BRACKET_TICK

: BRANCH ['] LIT COMPILE, 0 , ['] BRANCH0 COMPILE, ; IMMEDIATE

: REMOVE-MSB >R $0 DROP DROP R> ;

: MAIN 0 BRANCH0 [ HERE 0 , A.DUP A.>R ] 1 [ HERE A.SWAP BRANCH-DIST A.R> ! ] 2 ;

MAIN
