: DEFINE-STATES 0 ;
: STATE: DUP CONSTANT 1+ ;
: END-DEFINE-STATES-WITH-COUNT CONSTANT ;

( #states -- &state-list )
: <STATE-MACHINE CREATE 0 , HERE SWAP CELLS ALLOT ;
( &state-list state -- &state-list )
: STATE-BEHAVIOR: CELLS OVER + :NONAME SWAP ! ;
( &state-list -- )
: STATE-MACHINE> DROP ;
( &state-machine -- )
: RUN-STATE DUP @ 1 + CELLS + @ EXECUTE ;

DEFINE-STATES
STATE: LEVEL-INIT
STATE: LEVEL-DONE
END-DEFINE-STATES-WITH-COUNT NUM-LEVEL-STATES

