CREATE BASE-DEPTH 1 CELLS ALLOT
CREATE ACTUAL-DEPTH 1 CELLS ALLOT
CREATE ACTUAL-STACK 10 CELLS ALLOT

( count addr -- )
: PUSH-CELLS
  SWAP CELLS EACH ?DO
    I !
  1 CELLS +LOOP ;

\ TODO: Printing the failing test case would make these a lot nicer.
: T{ DEPTH BASE-DEPTH ! ;
: -> DEPTH
     DUP ACTUAL-DEPTH !
     BASE-DEPTH @ - ACTUAL-STACK PUSH-CELLS ;
: }T DEPTH ACTUAL-DEPTH @ <> IF ABORT" Unequal stacks." THEN
     DEPTH BASE-DEPTH @ - CELLS ACTUAL-STACK + ACTUAL-STACK ?DO
       I @ <> IF UNLOOP ABORT" Unexpected value." THEN
     1 CELLS +LOOP ;

